name: Eldizer Backend website  main Workflow

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying to live server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_SSH_HOST }}
          username: ${{ secrets.STAGING_SERVER_SSH_USERNAME }}
          password: ${{ secrets.STAGING_SERVER_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd /var/www/eldizer-website-backend/
            git checkout -f
            git pull
            php artisan migrate
            php artisan o:c
